### ISSUE TITLE
pip install fails with DistributionNotFound

### ISSUE THREAD

**Issue by nbeaver** [juhasch/PhysicalQuantities#69]
The package appears to be hosted on PyPi here:

https://pypi.python.org/pypi/physicalquantities/0.6.

However, attempting to install with `pip` fails regardless of capitalization:

    pip install --user PhysicalQuantities

Full log:

    ------------------------------------------------------------
    /usr/bin/pip run on Wed Jan 27 22:18:28 2016
    Downloading/unpacking PhysicalQuantities
      Getting page https://pypi.python.org/simple/PhysicalQuantities/
      URLs to search for versions for PhysicalQuantities:
      * https://pypi.python.org/simple/PhysicalQuantities/
      Analyzing links from page https://pypi.python.org/simple/physicalquantities/
      Could not find any downloads that satisfy the requirement PhysicalQuantities
    Cleaning up...
    No distributions at all found for PhysicalQuantities
    Exception information:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
        status = self.run(options, args)
      File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
        requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
      File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
        url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
      File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
        raise DistributionNotFound('No distributions at all found for %s' % req)
    DistributionNotFound: No distributions at all found for PhysicalQuantities

**Comment by r3sist** [comment]
@nbeaver I had a similar error. However you can use:
`pip install --user https://github.com/juhasch/PhysicalQuantities/archive/master.zip`
